[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /opt/nova/data/audit/audit.log
    Tag          nova.audit
    Refresh_Interval 10

[INPUT]
    Name         tail
    Path         /opt/nova/data/logs/*.log
    Tag          nova.system
    Refresh_Interval 10

[OUTPUT]
    Name         file
    Match        nova.*
    Path         /audit
    File         sovereign-audit.log

[OUTPUT]
    Name         stdout
    Match        nova.*
    Format       json_lines
